# exercÃ­cio 1.1

# print('teste de erro'
# print(teste)
print(2++2)
# print(02)
# print(2 5)
